INSERT INTO products(name, brand, category, price, description, image_filename, created_at) VALUES
('Galaxy S21', 'Samsung', 'Smartphone', 799.99, 'Flagship phone with 8GB RAM and 128GB storage', 'galaxy_s21.jpg', CURRENT_TIMESTAMP),
('iPhone 13', 'Apple', 'Smartphone', 999.99, 'Latest iPhone with A15 Bionic chip', 'iphone_13.jpg', CURRENT_TIMESTAMP),
('Xperia 5 III', 'Sony', 'Smartphone', 949.99, '5G smartphone with triple camera setup', 'xperia_5_iii.jpg', CURRENT_TIMESTAMP),
('OnePlus 9', 'OnePlus', 'Smartphone', 729.99, 'High-performance phone with Snapdragon 888', 'oneplus_9.jpg', CURRENT_TIMESTAMP),
('Pixel 6', 'Google', 'Smartphone', 699.99, 'Google\'s latest phone with advanced AI features', 'pixel_6.jpg', CURRENT_TIMESTAMP),
('Mi 11 Ultra', 'Xiaomi', 'Smartphone', 1199.99, 'Top-tier phone with 120Hz display', 'mi_11_ultra.jpg', CURRENT_TIMESTAMP),
('P50 Pro', 'Huawei', 'Smartphone', 1099.99, 'Premium phone with Leica camera technology', 'p50_pro.jpg', CURRENT_TIMESTAMP),
('Reno6 Pro', 'Oppo', 'Smartphone', 649.99, 'Slim design with powerful camera features', 'reno6_pro.jpg', CURRENT_TIMESTAMP),
('Find X3 Pro', 'Oppo', 'Smartphone', 1149.99, 'Flagship phone with 10-bit color depth', 'find_x3_pro.jpg', CURRENT_TIMESTAMP),
('ROG Phone 5', 'Asus', 'Smartphone', 999.99, 'Gaming phone with 144Hz refresh rate', 'rog_phone_5.jpg', CURRENT_TIMESTAMP),

('Moto G100', 'Motorola', 'Smartphone', 499.99, 'Affordable 5G phone with great battery life', 'moto_g100.jpg', CURRENT_TIMESTAMP),
('V60 ThinQ', 'LG', 'Smartphone', 799.99, 'Dual screen accessory option available', 'v60_thinq.jpg', CURRENT_TIMESTAMP),
('Redmi Note 10 Pro', 'Xiaomi', 'Smartphone', 299.99, 'Budget phone with 108MP camera', 'redmi_note_10_pro.jpg', CURRENT_TIMESTAMP),
('Nord 2', 'OnePlus', 'Smartphone', 399.99, 'Affordable mid-range with flagship features', 'nord_2.jpg', CURRENT_TIMESTAMP),
('Galaxy A52', 'Samsung', 'Smartphone', 499.99, 'Great value with IP67 water resistance', 'galaxy_a52.jpg', CURRENT_TIMESTAMP),
('Xperia 10 III', 'Sony', 'Smartphone', 449.99, 'Compact design with 21:9 OLED display', 'xperia_10_iii.jpg', CURRENT_TIMESTAMP),
('iPhone SE', 'Apple', 'Smartphone', 399.99, 'Compact iPhone with powerful A13 chip', 'iphone_se.jpg', CURRENT_TIMESTAMP),
('Moto G Power', 'Motorola', 'Smartphone', 249.99, 'Budget phone with long battery life', 'moto_g_power.jpg', CURRENT_TIMESTAMP),
('Realme 8 Pro', 'Realme', 'Smartphone', 299.99, 'Affordable with a 108MP camera', 'realme_8_pro.jpg', CURRENT_TIMESTAMP),
('Zenfone 8', 'Asus', 'Smartphone', 629.99, 'Compact flagship with Snapdragon 888', 'zenfone_8.jpg', CURRENT_TIMESTAMP),

('Axon 30', 'ZTE', 'Smartphone', 499.99, 'Under-display camera technology', 'axon_30.jpg', CURRENT_TIMESTAMP),
('Galaxy Z Fold3', 'Samsung', 'Smartphone', 1799.99, 'Foldable phone with S Pen support', 'galaxy_z_fold3.jpg', CURRENT_TIMESTAMP),
('iPhone 13 Pro Max', 'Apple', 'Smartphone', 1099.99, 'Top-tier iPhone with ProMotion display', 'iphone_13_pro_max.jpg', CURRENT_TIMESTAMP),
('RedMagic 6', 'Nubia', 'Smartphone', 599.99, 'Gaming phone with active cooling system', 'redmagic_6.jpg', CURRENT_TIMESTAMP),
('Vivo X70 Pro+', 'Vivo', 'Smartphone', 1099.99, 'Flagship with Zeiss optics and gimbal camera', 'vivo_x70_pro_plus.jpg', CURRENT_TIMESTAMP),
('Mi 11 Lite', 'Xiaomi', 'Smartphone', 299.99, 'Slim and light phone with AMOLED display', 'mi_11_lite.jpg', CURRENT_TIMESTAMP),
('Galaxy Note 20 Ultra', 'Samsung', 'Smartphone', 1299.99, 'Premium device with S Pen and 108MP camera', 'galaxy_note_20_ultra.jpg', CURRENT_TIMESTAMP),
('iPhone 12 Mini', 'Apple', 'Smartphone', 699.99, 'Compact design with powerful performance', 'iphone_12_mini.jpg', CURRENT_TIMESTAMP),
('Xperia 1 III', 'Sony', 'Smartphone', 1299.99, '4K OLED display with 120Hz refresh rate', 'xperia_1_iii.jpg', CURRENT_TIMESTAMP),
('Mate 40 Pro', 'Huawei', 'Smartphone', 1049.99, 'Flagship phone with advanced camera system', 'mate_40_pro.jpg', CURRENT_TIMESTAMP),

('Reno5 Pro', 'Oppo', 'Smartphone', 599.99, 'Mid-range phone with 65W fast charging', 'reno5_pro.jpg', CURRENT_TIMESTAMP),
('Realme GT', 'Realme', 'Smartphone', 499.99, 'Affordable with flagship Snapdragon 888', 'realme_gt.jpg', CURRENT_TIMESTAMP),
('Galaxy S20 FE', 'Samsung', 'Smartphone', 699.99, 'Affordable flagship with 120Hz display', 'galaxy_s20_fe.jpg', CURRENT_TIMESTAMP),
('Moto G Stylus', 'Motorola', 'Smartphone', 299.99, 'Budget phone with stylus support', 'moto_g_stylus.jpg', CURRENT_TIMESTAMP),
('iPhone 11', 'Apple', 'Smartphone', 599.99, 'Great value with A13 chip and dual cameras', 'iphone_11.jpg', CURRENT_TIMESTAMP),
('Redmi K40', 'Xiaomi', 'Smartphone', 399.99, 'Affordable with Snapdragon 870', 'redmi_k40.jpg', CURRENT_TIMESTAMP),
('Nord CE', 'OnePlus', 'Smartphone', 299.99, 'Mid-range phone with 90Hz display', 'nord_ce.jpg', CURRENT_TIMESTAMP),
('Xperia 5 II', 'Sony', 'Smartphone', 849.99, 'Compact flagship with 120Hz display', 'xperia_5_ii.jpg', CURRENT_TIMESTAMP),
('Galaxy Z Flip3', 'Samsung', 'Smartphone', 999.99, 'Foldable phone with compact design', 'galaxy_z_flip3.jpg', CURRENT_TIMESTAMP),
('Find X2 Pro', 'Oppo', 'Smartphone', 1199.99, 'Flagship with top-tier specs and design', 'find_x2_pro.jpg', CURRENT_TIMESTAMP),

('Mate X2', 'Huawei', 'Smartphone', 2299.99, 'Premium foldable phone with advanced features', 'mate_x2.jpg', CURRENT_TIMESTAMP),
('iPhone XS Max', 'Apple', 'Smartphone', 999.99, 'Large screen iPhone with OLED display', 'iphone_xs_max.jpg', CURRENT_TIMESTAMP),
('Galaxy S10+', 'Samsung', 'Smartphone', 899.99, 'Premium phone with triple camera setup', 'galaxy_s10_plus.jpg', CURRENT_TIMESTAMP),
('Xperia XZ3', 'Sony', 'Smartphone', 799.99, 'Phone with HDR OLED display and 4K recording', 'xperia_xz3.jpg', CURRENT_TIMESTAMP),
('Mi Mix Fold', 'Xiaomi', 'Smartphone', 1799.99, 'Foldable phone with liquid lens technology', 'mi_mix_fold.jpg', CURRENT_TIMESTAMP),
('Nova 9', 'Huawei', 'Smartphone', 499.99, 'Mid-range phone with sleek design', 'nova_9.jpg', CURRENT_TIMESTAMP),
('Zenfone 7 Pro', 'Asus', 'Smartphone', 849.99, 'Flip camera design for selfies and main shots', 'zenfone_7_pro.jpg', CURRENT_TIMESTAMP),
('Find N2', 'Oppo', 'Smartphone', 1399.99, 'Foldable phone with stunning display', 'find_n2.jpg', CURRENT_TIMESTAMP),
('Nubia Z30 Pro', 'Nubia', 'Smartphone', 699.99, 'High-performance phone with Snapdragon 888+', 'nubia_z30_pro.jpg', CURRENT_TIMESTAMP),
('Galaxy A72', 'Samsung', 'Smartphone', 449.99, 'Mid-range with telephoto camera and 90Hz display', 'galaxy_a72.jpg', CURRENT_TIMESTAMP);